\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename anju.info
@settitle Anju User Guide
@documentencoding UTF-8
@documentlanguage en
@syncodeindex pg cp
@paragraphindent none
@c %**end of header

@copying
Copyright © 2026 Charles Y@. Choi
@end copying

@dircategory Emacs misc features
@direntry
* Anju: (anju).         A package for customizing Emacs mouse interactions.
@end direntry

@finalout
@titlepage
@title Anju User Guide
@subtitle for version 1.2.2-rc.1
@author Charles Y@. Choi (@email{kickingvegas@@gmail.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Anju User Guide

Version: 1.2.2-rc.1

Copyright © 2026 @w{Charles Y. Choi}

Anju (안주) is a project to align mouse interactions in Emacs with contemporary (circa 2026) expectations. Effort towards this alignment is made in the following areas:

@itemize
@item
Context-sensitive menus
@item
De-emphasis of middle mouse button usage (binding @samp{<mouse-2>})
@item
Support direct manipulation when possible
@item
Re-organization of the main menu bar
@end itemize

The features offered by Anju are opinionated, but avoids unconventional behavior. Anju aspires to bring a calmer mouse experience to Emacs.

Please note that all UI terminology in this document is Emacs-centric and differs from conventional GUI terminology. Refer to (emacs) Frames (@ref{Frames,emacs#Frames,,emacs,}) for more detail on this.

It costs money to make, enhance, and maintain Anju as ideologically free software. If you enjoy using Anju, please buy me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas}

@end ifnottex

@menu
* Motivation::
* Features::
* Requirements::
* Install::
* Customization::
* Future Work::
* Feedback & Discussion::
* Sponsorship::
* About Anju::
* Acknowledgments::
* Main Index::
* Variable Index::

@detailmenu
--- The Detailed Node Listing ---

Motivation

* Design Principles and Concerns::

Features

* Mode Line Features::
* Context Menu Features::
* Main Menu Features::
* Window Management Features::

Context Menu Features

* Selected Text Commands::
* Org Mode Context Menu::
* Dired Mode Context Menu::
* Magit Support::

Org Mode Context Menu

* Org Headline Context Menu::
* Org Item Context Menu::
* Org Table Context Menu::
* Org Paste Context Menu::

Main Menu Features

* File Menu Features::
* Edit Menu Features::
* Options Menu Features::
* Bookmarks Menu Features::
* Text Menu Features::
* Index Menu (imenu) Features::
* Help Menu Features::

Customization

* Anju Initialization (@code{anju-init})::
* Context Menu Customization::
* Mode Line Buffer List Menu Customization::
* Main Menu Customization::

Context Menu Customization

* Anju Context Menu Functions::

Main Menu Customization

* File Menu Customization::
* Edit Menu Customization::
* Options Menu Customization::
* Text Menu Customization::
* Bookmarks Menu Customization::
* Help Menu Customization::
* Imenu Menu Customization::

@end detailmenu
@end menu

@node Motivation
@chapter Motivation

@cindex Motivation

The Anju package is intended to change the default mouse interactions in Emacs for the following reasons:

@itemize
@item
Uneven implementation of context-sensitive menus for different modes.
@item
Over-commitment to legacy usage of the middle mouse button.
@item
Lengthy menus that feel more like an inventory of commands rather than a designed user experience.
@item
Over-reliance on mouse workflows that require switching between the mouse and keyboard.
@end itemize

Anju makes opinionated design decisions, but avoids unconventional behavior. Anju aspires to bring a calmer mouse experience to Emacs.

Elaboration on what informs Anju's opinions is described below.

@menu
* Design Principles and Concerns::
@end menu

@node Design Principles and Concerns
@section Design Principles and Concerns

@cindex Design Principles and Concerns

This section conveys the principles and concerns used by Anju to inform its design decisions.

Editorially, all design decisions for Anju are ultimately the opinion of Charles Y@. Choi.


@subheading General Principles

@itemize
@item
Menus should be organized.
@itemize
@item
A coherent information architecture should be conveyed.
@item
Balance between concision and discoverability should be made in a menu's offerings.
@end itemize
@item
Nesting of sub-menus should be carefully considered, ideally not exceeding a depth of two.
@item
Mouse workflows that require keyboard input should be minimized.
@item
If the opportunity to provide a direct manipulation experience is available, it should be taken.
@item
Unconventional mouse interactions should be avoided.
@end itemize

@subheading Concerns

Anju takes the position that different types of menus have different concerns or objectives. This is most apparent in contrasting the design of a main menu section (e.g. File, Edit, Options, …) to that of a context menu.

For Anju:

@itemize
@item
The highest concern of a main menu section is discoverability.
@item
The highest concern of a context menu is concision.
@end itemize

A common implementation practice in Emacs is to reuse menu keymaps for both the main menu and context menus. This violates the above concerns, which Anju seeks to address.

The next sub-sections further detail the design concerns with respect to an area where mouse interaction occurs.

@subsubheading Context Menu

A context menu (as its name implies) should constrain itself to commands relevant to @emph{context}. The parameters of this context are usually (although not exclusively) defined by a subset of:

@itemize
@item
Point (cursor) position
@item
Text selection
@item
Mouse cursor position
@item
Major mode
@item
Read-only state (on or off)
@end itemize

Anju takes the opinion that context menus should @emph{not} support general command discovery. The context menu offering should be @emph{concise}. Users seeking command discovery should instead look at the main menu.

@subsubheading Direct Manipulation

Support for direct action based on mouse cursor position is a common user interaction technique. Anju applies this to Emacs window management, where window creation, deletion, and swapping are supported from both the context menu and the mode line.

@subsubheading No Middle Button Bindings

Anju eschews Emacs' default middle mouse button bindings as they presume usage of a @uref{https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Sun_optical_mouse.jpg/960px-Sun_optical_mouse.jpg, 90's style 3-button mouse}. This style of mouse design has long been superseded with a middle @uref{https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg, scroll-wheel+button control}. This widespread hardware change has resulted in the majority of mouse-supporting applications to emphasize scrolling actions with the middle control and clicking actions to the left and right buttons. Anju follows suit, primarily binding the right mouse button click (down) event to raising a context menu. In addition, Anju reconfigures commands that were previously bound to the middle button to ones accessible via a context menu.

The only exception Anju makes in this matter is to keep the Emacs default binding of @code{mouse-2} to @code{mouse-yank-primary}.

@node Features
@chapter Features

@cindex Features

Anju offers many enhancements to the mouse interactions provided by Emacs. These enhancements are detailed in the following sections below.

@menu
* Mode Line Features::
* Context Menu Features::
* Main Menu Features::
* Window Management Features::
@end menu

@node Mode Line Features
@section Mode Line Features

@cindex Mode Line Features

The following mode line enhancements are provided by Anju:

@subheading Pop-up Buffer List
@cindex Pop-up Buffer List

On the mode line, left-click (@code{mouse-1}) on the buffer name to raise a pop-up menu containing a list of open buffers. The contents of this list is controlled by the customizable variable @code{anju-buffer-list-filter-functions}. More info on customizing the buffer list menu can be found in @ref{Mode Line Buffer List Menu Customization}.


@image{images/anju-mode-line-buffer-list,,,,png}

@subheading Window Management
@cindex Window Management

A right-click (@code{mouse-3}) on any blank space on the mode line will pop-up a window management menu.

@image{images/anju-mode-line-window-management,,,,png}

From here, one can:
@itemize
@item
Delete the window (×)
@item
Split the window horizontally (→)
@item
Split the window vertically (↓)
@item
If multiple windows are shown, swap the current window.
@end itemize

Note: usage of ``window'' refers to the Emacs definition of it. Refer to @ref{Frames,emacs#Frames,,emacs,} for more detail on this.

@subheading Toggle Maximize Window
@cindex Toggle Maximize Window

A left-double-click on any blank space on the mode line will checkpoint the current window configuration, then maximize the current window (@code{delete-other-windows}). Re-doing the left-double-click will restore the prior window configuration.

@node Context Menu Features
@section Context Menu Features

@cindex Context Menu Features

Anju enhances @code{context-menu-mode} by providing context menu functions to support the following contexts:

@itemize
@item
Selected text
@item
Mode-specific commands
@itemize
@item
Org mode
@item
Dired
@end itemize
@item
Window management
@item
Full support for @code{context-menu-mode} customization (See @ref{Context Menu Customization}).
@end itemize

Anju deliberately omits the display of the default mode-specific menu keymaps in the context menu as they are considered redundant to their display in the main menu. Rationale for this is described in @ref{Design Principles and Concerns}. Users can still access the default mode-specific menu keymap by using the binding @kbd{C-<mouse-3>}.

Learn more about the different areas Anju enhances context menus in the links below.

@menu
* Selected Text Commands::
* Org Mode Context Menu::
* Dired Mode Context Menu::
* Magit Support::
@end menu

@node Selected Text Commands
@subsection Selected Text Commands

@cindex Selected Text Commands

@image{images/anju-context-menu-region,,,,png}

If a context menu is raised on selected text, the following menu items are displayed:

@table @asis
@item Occur
Run @code{occur} command to show occurrences of selected text.

@item Style
Applies mode-specific markup to emphasize the selected text (e.g. bold, italic, code, etc.).
@itemize
@item
Available only for @code{org-mode} and @code{markdown-mode}.
@end itemize

@item Transform Text
Applies transforms (upper/lower case, capitalize) to the selected text.

@item Toggle comment 
Toggles selected text to be commented based on mode.
@itemize
@item
Available only on modes derived from @code{prog-mode} and @code{org-mode}
@end itemize

@item Write Region
Writes selected text to a user-specified file.

@item Look Up
If a word is selected, uses @code{dictionary} to look up its definition.
@end table

@node Org Mode Context Menu
@subsection Org Mode Context Menu

@cindex Org Mode Context Menu

Anju provides context-sensitive support for Org mode by providing commands relevant to the type of Org element the point is in. Org elements supported by Anju are:

@itemize
@item
Headline
@item
Item
@item
Table
@end itemize

In addition if text is selected, then support for styling it is supported.

Note that the Org mode context menu is intentionally restrained in its command offering in accord with Anju's @ref{Design Principles and Concerns}.

It is recommended that the @code{org-mouse} package be loaded when using

@menu
* Org Headline Context Menu::
* Org Item Context Menu::
* Org Table Context Menu::
* Org Paste Context Menu::
@end menu

@node Org Headline Context Menu
@subsubsection Org Headline Context Menu

@cindex Org Headline Context Menu

If the context menu is raised on a headline, then commands related to clocking and promotion are offered.

@image{images/anju-context-menu-org-headline,,,,png}

@node Org Item Context Menu
@subsubsection Org Item Context Menu

@cindex Org Item Context Menu

If the context menu is raised on a list item, then commands related to promotion and conversion to a checkbox are provided.

The menu item ``To Checkbox'' will convert an item to a checkbox, with the additional behavior that if the point is at the start of the whole list, the whole list will be turned into checkboxes.

@image{images/anju-context-menu-org-item,,,,png}

If @code{org-mouse} is loaded, then clicking on a checkbox will toggle its state between on ('[X]') or off ('[ ]'). However, changing to an intermediate state ('[-]') is supported by the menu item ``In-Progress''. The menu item ``To Item'' will convert the checkbox back to a plain list item.

@image{images/anju-context-menu-org-checkbox,,,,png}

Note that checkboxes in screenshots are prettified using @code{prettify-symbols-mode}.

@node Org Table Context Menu
@subsubsection Org Table Context Menu

@cindex Org Table Context Menu

If the context menu is raised in a table, then table-specific commands are shown.

@image{images/anju-context-menu-org-table,,,,png}

@node Org Paste Context Menu
@subsubsection Org Paste Context Menu

@cindex Org Paste Context Menu

@image{images/anju-context-menu-enhanced-paste,,,,png}

Anju adds more “Paste” commands that will display given the right context.

@table @asis
@item Paste Last Org Link
If it exists, this command will insert the last stored Org link.

@item Paste Markdown as Org
If the clipboard (latest yank) is known by the user to be Markdown text, this command will convert the clipboard text to Org via @code{pandoc}, then paste (yank) it into the buffer.

@item Paste Media
If an image as been copied into the clipboard, this menu item will ``paste'' it via the @code{yank-media} command.
@end table

@node Dired Mode Context Menu
@subsection Dired Mode Context Menu

@cindex Dired Mode Context Menu

Anju has context menu support for Dired mode. The screenshot below shows the context menu when the mouse point is over a file.

@image{images/anju-dired-copy-to,,,,png}

If the mouse point is over a directory, the option to insert a view (aka subdir) for it in the buffer is provided.

@image{images/anju-dired-insert-subdir,,,,png}

Note that the Dired context menu is intentionally restrained in its command offering in accord with Anju's @ref{Design Principles and Concerns}.

@node Magit Support
@subsection Magit Support

@cindex Magit Support

If Magit 4.4+ is installed, then the context menu function @code{anju-context-menu-vc} will offer Magit commands depending on context. If the context menu is raised in a file buffer, then the menu item ``Magit Dispatch…'' (@code{magit-file-dispatch}) is shown, otherwise ``Magit Status'' (@code{magit-status}).

@node Main Menu Features
@section Main Menu Features

@cindex Main Menu Features

Anju enhances the main menu bar of Emacs by making opinionated changes to its existing menus as well as adding several new ones. These changes are configurable per menu in the main menu (e.g. ``File'', ``Edit'', ``Options'', etc.). For more detail, see @ref{Main Menu Customization}.

@menu
* File Menu Features::
* Edit Menu Features::
* Options Menu Features::
* Bookmarks Menu Features::
* Text Menu Features::
* Index Menu (imenu) Features::
* Help Menu Features::
@end menu

@node File Menu Features
@subsection File Menu Features

@cindex File Menu Features

Anju makes the following modifications to the main menu bar @strong{File} menu:

@itemize
@item
Adds a “Swap Window ›” sub-menu.
@item
Updates the “New Frame on Display Server@dots{}” menu item to only display on an X11 system.
@item
Updates the “New Frame on Monitor…” menu item to only display if more than one monitor is detected.
@end itemize

For the macOS NS variant of Emacs, the above update to “New Frame on Monitor…” will only work on Emacs version 31+.

These modifications are optional. For more detail, see @ref{File Menu Customization}.

@node Edit Menu Features
@subsection Edit Menu Features

@cindex Edit Menu Features

@image{images/anju-main-menu-edit-search-in-files,,,,png}

Anju makes the following modifications to the main menu bar @strong{Edit} menu:

@itemize
@item
Adds “Search in Files…” to the @strong{Search} sub-menu.

@item
Adds the “Transpose  ⇄” sub-menu of commands to transpose different text quantities.

@item
Adds the “Move Text” sub-menu to move different text quantities.

@item
Adds the “Delete” sub-menu to delete different text quantities.

@item
Adds the menu item “Flush Lines…”.

@item
Adds the menu item “Keep Lines…”.

@item
Adds the menu item “Duplicate”.
@end itemize

On the macOS NS variant of Emacs, the following menu items are added.

@itemize
@item
“Colors” - display the macOS system color picker dialog.

@item
“Emoji & Symbols” - display the macOS system Emoji & Symbols dialog.
@end itemize


The commands provided by the above additions to the @strong{Edit} menu are shown below.


@itemize
@item
Search
@itemize
@item
Search in Files… (@code{rgrep})
@end itemize

@item
Transpose ⇄
@itemize
@item
Characters (@code{transpose-chars})
@item
Words (@code{transpose-words})
@item
Lines (@code{transpose-lines})
@item
Sentences (@code{transpose-sentences})
@item
Paragraphs (@code{transpose-paragraphs})
@item
Regions (@code{transpose-regions})
@item
Balanced Expressions (sexps) (@code{transpose-sexps})
@end itemize

@item
Move Text
@itemize
@item
Word → (@code{casual-editkit-move-word-forward})
@item
Word ← (@code{casual-editkit-move-word-backward})
@item
Sentence → (@code{casual-editkit-move-sentence-forward})
@item
Sentence ← (@code{casual-editkit-move-sentence-backward})
@item
Balanced Expression (sexp) → (@code{casual-editkit-move-sexp-forward})
@item
Balanced Expression (sexp) ← (@code{casual-editkit-move-sexp-backward})
@end itemize

@item
Delete
@itemize
@item
Join Line (@code{join-line})
@item
Just One Space (@code{just-one-space})
@item
Delete Horizontal Space (@code{delete-horizontal-space})
@item
Delete Blank Lines (@code{delete-blank-lines})
@item
Whitespace Cleanup (@code{whitespace-cleanup})
@item
Delete Trailing Whitespace (@code{delete-trailing-whitespace})
@item
Zap up to… (@code{zap-up-to-char})
@item
Zap to… (@code{zap-to-char})
@end itemize

@item
Flush Lines… (@code{flush-lines})

@item
Keep Lines… (@code{keep-lines})

@item
Duplicate (@code{duplicate-dwim})

@item
Colors (@code{ns-popup-color-panel}) (only on  macOS NS)

@item
Emoji & Symbols (@code{ns-do-show-character-palette}) (only on macOS NS)
@end itemize


Note that a menu command can be run again immediately after it has been issued using the @code{repeat} command (binding @kbd{C-x z}). This is useful when using the move text commands.

These modifications are optional. For more detail, see @ref{Edit Menu Customization}.

@node Options Menu Features
@subsection Options Menu Features

@cindex Options Menu Features

Anju makes the presumption that most Emacs users do not use the CUA mode configuration in the main menu bar @strong{Options} menu. As such, the “Cut/Paste with C-x/C-c/C-v (CUA Mode)” menu item is removed.

This modification is optional. For more detail, see @ref{Options Menu Customization}.

@node Bookmarks Menu Features
@subsection Bookmarks Menu Features

@cindex Bookmarks Menu Features

Anju adds a @strong{Bookmarks} menu to the main menu to work with Emacs-specific bookmarks.

@image{images/anju-main-menu-bookmarks,,,,png}

This modification is optional. For more detail, see @ref{Bookmarks Menu Customization}.

The menu hierarchy of the @strong{Bookmarks} menu is described below with the actual command shown in parenthesis next to its label.

@itemize
@item
Edit Bookmarks (@code{list-bookmarks})
@item
Add Bookmark… (@code{bookmark-set-no-overwrite})
@item
Jump to Bookmark… (@code{bookmark-jump})
@end itemize

@node Text Menu Features
@subsection Text Menu Features

@cindex Text Menu Features

@image{images/anju-main-menu-text,,,,png}

If the major mode of the current buffer is derived from @code{text-mode}, then a @strong{Text} menu is displayed in the main menu bar.

The menu hierarchy of the @strong{Text} menu is described below with the actual command shown in parenthesis next to its label.

@itemize
@item
Transform Text (@code{anju-transform-text-menu})
@itemize
@item
Make Upper Case (@code{upcase-region})
@item
Make Lower Case (@code{downcase-region})
@item
Capitalize (@code{capitalize-region})
@end itemize

@item
Style (@code{anju-style-menu})
@itemize
@item
Bold (@code{anju-style-bold})
@item
Italic (@code{anju-style-italic})
@item
Code (@code{anju-style-code})
@item
Underline (@code{anju-style-underline})
@item
Verbatim (@code{anju-style-verbatim})
@item
Strike Through (@code{anju-style-strike-through})
@item
Remove (@code{anju-style-remove})
@end itemize

@item
Center (@code{anju-center-text-menu})
@itemize
@item
Line (@code{center-line})
@item
Region (@code{center-region})
@item
Paragraph (@code{center-paragraph})
@end itemize

@item
Fill (@code{anju-fill-text-menu})
@itemize
@item
Paragraph (@code{fill-paragraph})
@item
Region (@code{fill-region})
@item
Region as paragraph (@code{fill-region-as-paragraph})
@item
Individual paragraphs (@code{fill-individual-paragraphs})
@item
Non-uniform paragraphs (@code{fill-nonuniform-paragraphs})
@end itemize

@item
Auto Fill (@code{toggle-text-mode-auto-fill})
@end itemize

Note the @strong{Style} menu is visible only for Org and Markdown modes.

This modification is optional. For more detail, see @ref{Text Menu Customization}.

@node Index Menu (imenu) Features
@subsection Index Menu (imenu) Features

@cindex Index Menu Features

@image{images/anju-main-menu-imenu,,,,png}


For certain modes that support Imenu (@ref{Imenu,emacs#Imenu,,emacs,}), Anju will add an @strong{Index} menu to the main menu bar via the function  @code{imenu-add-menubar-index}.

Modes supported this way by Anju are:

@itemize
@item
@code{prog-mode} derived modes
@item
@code{org-mode}
@item
@code{markdown-mode}
@item
@code{makefile-mode}
@end itemize

This modification is optional. For more detail, see @ref{Imenu Menu Customization}.

@node Help Menu Features
@subsection Help Menu Features

@cindex Help Menu Features

Anju re-organizes the @strong{Help} menu as shown below. The re-organization emphasizes showing documentation in a new frame, takes out non-help related menu items, and offers more concision.

@image{images/anju-main-menu-help,,,,png}

This modification is optional. For more detail, see @ref{Help Menu Customization}.

For experienced users, the ``Emacs Tutorial'' menu items can be removed via the customizable variable @code{anju-help-menu-remove-emacs-tutorial}.

@node Window Management Features
@section Window Management Features

@cindex Window Management Features

Window management via mouse interaction is provided for through the @ref{Mode Line Features, , mode line} and @ref{Context Menu Features, , context menu}. More detail is provided in those sections.

@node Requirements
@chapter Requirements

@cindex Requirements

Anju requires Emacs 29.1+, Casual 2.13+, Markdown Mode 2.7+.

Certain menus require more installed software:

@itemize
@item
Anju Dired Support: GNU Coreutils (@code{ls})
@item
Markdown import to Org: pandoc
@end itemize

Anju provides optional support for Magit 4.4+.

@node Install
@chapter Install

@cindex Install
@vindex context-menu-mode
@vindex anju-init

Basic installation of Anju composes of two parts:

@enumerate
@item
Turn on @code{context-menu-mode} to major modes of preference. This is done using the @code{add-hook} function as shown below.
@lisp
(add-hook 'prog-mode-hook #'context-menu-mode)
(add-hook 'text-mode-hook #'context-menu-mode)
(add-hook 'dired-mode-hook #'context-menu-mode)
(add-hook 'shell-mode-hook #'context-menu-mode)
@end lisp

@item
Call @code{anju-init} in your Emacs initialization file.

@lisp
(anju-init)
@end lisp
@end enumerate

Anju supports a high degree of customization. Users who wish this should make a deep read of the @ref{Customization} section.

While not required, the following additions to your Emacs initialization file can further enhance your mouse experience:

@itemize
@item
Enable @code{org-mouse}
@lisp
(require 'org-mouse)
@end lisp

@item
Add Markdown export support to Org mode
@itemize
@item
@code{M-x} @code{customize-variable} @code{org-export-backends}, check @code{md} option.
@end itemize

@item
Globally bind @code{C-x 1} to @code{anju-toggle-one-window}.

@lisp
(keymap-global-set "C-x 1" #'anju-toggle-one-window)
@end lisp

@item
Set @code{use-file-dialog} to @code{t} to support mouse-driven-only dialog interactions, or @code{nil} to always get a mini-buffer prompt.
@end itemize

@node Customization
@chapter Customization

@cindex Customization

Anju provides a number of ways to customize mouse interactions in Emacs. In many cases, Anju leverages off existing Emacs customization options, particularly around defining and modifying menus. Users who wish to modify menus in Emacs should familiarize themselves with menu keymaps (@ref{Menu Keymaps,elisp#Menu Keymaps,,elisp,}) and the Easy Menu (@ref{Easy Menu,elisp#Easy Menu,,elisp,}) library.

Customization options for the different areas Anju covers are detailed below.

@menu
* Anju Initialization (@code{anju-init})::
* Context Menu Customization::
* Mode Line Buffer List Menu Customization::
* Main Menu Customization::
@end menu

@node Anju Initialization (@code{anju-init})
@section Anju Initialization (@code{anju-init})

@cindex Anju Initialization
@vindex anju-init
@vindex anju-reconfigure-context-menu-functions-enable
@vindex anju-mode-line-bindings-enable
@vindex anju-unset-legacy-mouse-bindings-enable
@vindex anju-reconfigure-main-menu-enable
@vindex anju-help-menu-remove-emacs-tutorial
@vindex anju-reconfigure-main-menu-hook

Anju has a number of customizable variables that determine the behavior of @code{anju-init}. They are:

@table @asis
@item @code{anju-reconfigure-context-menu-functions-enable}
Enable reconfiguration of the variable @code{context-menu-functions} with Anju-defined menu functions.

If @code{context-menu-functions} is previously set via @code{customize-variable} then @code{anju-init} will make no changes to @code{context-menu-functions} regardless of how  @code{anju-reconfigure-context-menu-functions-enable} is set.

@item @code{anju-mode-line-bindings-enable}
Enable Anju-defined bindings for the mode line.

@item @code{anju-unset-legacy-mouse-bindings-enable}
Remove bindings using @code{mouse-2}.

@item @code{anju-reconfigure-main-menu-enable}
Top-level variable to reconfigure the main menu.

If @code{anju-reconfigure-main-menu-enable} is @code{t}, the following variables determine how the main menu is reconfigured:

@table @asis
@item @code{anju-reconfigure-main-menu-hook}
a list of functions, each modifying a menu of the main menu.

@item @code{anju-help-menu-remove-emacs-tutorial}
control if the Emacs tutorial menu items are shown.
@end table
@end table

By default, all the above @code{*-enable} variables are set to @code{t}.  Users preferring to make granular changes to @code{anju-init} can invoke @code{M-x} @code{customize-group} @code{anju}.

@node Context Menu Customization
@section Context Menu Customization

@cindex Context Menu Customization
@vindex context-menu-mode
@vindex context-menu-functions


Anju uses @code{context-menu-mode} (introduced in Emacs 28) to define its context menu behavior. This is accomplished through the customizable hook variable @code{context-menu-functions}.

@code{context-menu-functions} is a list of functions where each function has two arguments:

@itemize
@item
@code{menu} : reference to the context menu
@item
@code{click} : a mouse event
@end itemize

When the context menu is raised, typically via right-click (@code{mouse-3}), each function in @code{context-menu-functions} is run, populating the context menu.

The following example Elisp illustrates an implementation of a context menu function.

@lisp
(defun anju-context-menu-wordcount (menu click)
  "Context menu hook function for wordcount commands.

- MENU: menu
- CLICK: event

This function is intended to be hooked into `context-menu-functions'."
  (when (and (derived-mode-p 'text-mode) (not (anju-at-org-table-p)))
    (save-excursion
      (mouse-set-point click)
      (anju-context-menu-item-separator menu count-words-separator)
      (easy-menu-add-item menu nil [count-words count-words
                                    :label "Count Words"
                                    :help "Count words"])))
  menu)
@end lisp


Defining how a menu item is context-sensitive can be determined in multiple places:

@enumerate
@item
At the time of menu item definition
@item
At a higher level.
@end enumerate

The @emph{context} is determined by a predicate which can take into account different things, among them:

@itemize
@item
Selected Text (@code{use-region-p})
@item
Major mode
@item
Cursor (Point) position
@item
Mouse position
@end itemize

In the example above, the context predicate tests if the major mode is derived from @code{text-mode} @emph{and} if point is not inside an Org table (@code{anju-at-org-table-p}).  Note that it is defined at a higher level to avoid instantiating menu items if the context does not apply.

The context predicate can be embedded in the menu item definition itself. See more about this with the @code{:visible} and @code{:active} keywords for the macro @code{easy-menu-define} (@ref{Easy Menu,elisp#Easy Menu,,elisp,}).

It is up to the implementer to determine where to best define and apply the context predicate.

@subheading Customizing context-menu-functions

It is recommended to use the @code{customize-variable} command to configure @code{context-menu-functions} instead of using @code{add-hook} for the following reasons:

@enumerate
@item
A visual UI is provided showing what choices for built-in context menu functions are available.
@item
Users can insert their own custom function.
@item
Top-down ordering of functions will similarly determine the order of menu items in the context menu.
@end enumerate

@menu
* Anju Context Menu Functions::
@end menu

@node Anju Context Menu Functions
@subsection Anju Context Menu Functions

@vindex anju-context-menu-dired
@vindex anju-context-menu-org-mode
@vindex anju-context-menu-scratch
@vindex anju-context-menu-buffers
@vindex anju-context-menu-region
@vindex anju-context-menu-region-extension
@vindex anju-context-menu-narrow
@vindex anju-context-menu-open-in
@vindex anju-context-menu-vc
@vindex anju-context-menu-markup
@vindex anju-context-menu-wordcount
@vindex anju-context-menu-window
@vindex anju-context-menu-dictionary

Anju provides the following context menu functions for convenience. They can be used as-is or serve as a base for user-customized behavior.

@table @asis
@item @code{anju-context-menu-dired}
Dired commands.

@item @code{anju-context-menu-org-mode} 
Org mode commands.

@item @code{anju-context-menu-scratch} 
Open scratch buffer.

@item @code{anju-context-menu-buffers}
Buffer navigation commands.

@item @code{anju-context-menu-region}
Commands for selected text.

@item @code{anju-context-menu-region-extension}
Commands for extending the menu items provided by the built-in @code{context-menu-region} hook. Anju puts the Org-dependent “Paste” commands here.

@item @code{anju-context-menu-dictionary}
Look up definition of selected word with @code{dictionary}.

@item @code{anju-context-menu-narrow}
Narrow-related commands.

@item @code{anju-context-menu-open-in}
Open in Dired.

@item @code{anju-context-menu-vc}
Version control related commands.
If Magit 4.4+ is installed, then calls to it are made from here.

@item @code{anju-context-menu-markup}
Commands to show/hide text markup (e.g. Org, Markdown).

@item @code{anju-context-menu-wordcount}
Word count command.

@item @code{anju-context-menu-window}
Window management commands.
@end table

@node Mode Line Buffer List Menu Customization
@section Mode Line Buffer List Menu Customization

@cindex Mode Line Buffer List Menu Customization
@vindex anju-buffer-list-filter-functions
@vindex anju-mode-line-buffer-list-function
@vindex anju-buffer-list-plain-filter
@vindex anju-buffer-list-compilation-filter
@vindex anju-buffer-list-grep-filter
@vindex anju-buffer-list-xref-filter
@vindex anju-buffer-list-eshell-filter
@vindex anju-buffer-list-shell-filter
@vindex anju-buffer-list-info-filter
@vindex anju-buffer-list-help-filter
@vindex anju-buffer-list-menu-items
@vindex anju-popup-buffer-menu

The pop-up buffer list menu can be customized two ways:

@enumerate
@item
Customizing the variable @code{anju-buffer-list-filter-functions}, a list of filter functions that are run each time the pop-up menu is raised when left-clicking the mode line buffer name.

@item
Customizing the variable @code{anju-mode-line-buffer-list-function}, which gives a user complete control on what is displayed in the pop-up menu.
@end enumerate


@subheading anju-buffer-list-filter-functions

This variable is an alist used by the function @code{anju-buffer-list-menu-items} to populate the list of buffers used in the pop up menu @code{anju-popup-buffer-menu}.

This alist is filled using the following key, value pair types:

@table @asis
@item key
a buffer list filter function
@item value
integer used as the maximum count of buffers to use from the filter function
@end table

The buffer list filter function is of the form @code{(filter-fn (buffers &optional count))} where buffers is a list of buffers (usually @code{buffer-list}) and count is the maximum count of buffers to use.

The order of the buffer list presumes the most recently used buffers are
at the front of the list.

Anju provides the following buffer filters:

@table @asis
@item @code{anju-buffer-list-plain-filter}
buffers whose name is not marked as special (a name wrapped in ‘*’).
@item @code{anju-buffer-list-compilation-filter}
buffers whose major mode is @code{compilation-mode}.
@item @code{anju-buffer-list-grep-filter}
buffers whose major mode is @code{grep-mode}.
@item @code{anju-buffer-list-xref-filter}
buffers whose major mode is @code{xref--xref-buffer-mode}.
@item @code{anju-buffer-list-eshell-filter}
buffers whose major mode is @code{eshell-mode.}
@item @code{anju-buffer-list-shell-filter}
buffers whose major mode is @code{shell-mode}.
@item @code{anju-buffer-list-info-filter}
buffers whose major mode is @code{Info-mode}.
@item @code{anju-buffer-list-help-filter}
buffers whose major mode is @code{help-mode}.
@end table

Users can customize @code{anju-buffer-list-filter-functions} to re-compose or add their own filters to define the resulting buffer list returned by @code{anju-buffer-list-menu-items}. It is recommended that the @code{customize-variable} command be used to accomplish this.

@subheading anju-mode-line-buffer-list-function
@vindex anju-mode-line-buffer-list-function

Function that populates the mode line buffer name popup menu.

Assign this variable to a function that returns a value that conforms to the @code{MENU} parameter of the command @code{popup-menu}.

This setting allows for customization of the buffer list (or any other menu content) when the mode line buffer name (identifier) is clicked (typically with @code{mouse-1}).

Users who wish define their own menu should override this value with their own function. It is recommended that such users look at the source to @code{anju-buffer-list-menu-items} as a start to defining their own menu function.

@node Main Menu Customization
@section Main Menu Customization

@cindex Main Menu Customization

Anju uses the customizable hook variable @code{anju-reconfigure-main-menu-hook} to customize the main menu bar.

@code{anju-reconfigure-main-menu-hook} is a list of hook functions,  where each function is designed to modify a different menu of the main menu bar (e.g. ``File'', ``Edit'', ``Options'', etc.). This hook is run in the command @code{anju-init}.

Detailed below are the different hook functions provided for by Anju.

Users are free to implement their own hook functions to add to @code{anju-reconfigure-main-menu-hook}. Users who wish to do this should familiarize themselves with menu keymaps (@ref{Menu Keymaps,elisp#Menu Keymaps,,elisp,}) and the Easy Menu (@ref{Easy Menu,elisp#Easy Menu,,elisp,}) library.

Note that Anju's implementation of hook functions to each affect a specific menu in the main menu bar is by convention.

For more info on hook variables see @ref{Hooks,emacs#Hooks,,emacs,}.

@menu
* File Menu Customization::
* Edit Menu Customization::
* Options Menu Customization::
* Text Menu Customization::
* Bookmarks Menu Customization::
* Help Menu Customization::
* Imenu Menu Customization::
@end menu

@node File Menu Customization
@subsection File Menu Customization

@cindex File Menu Customization
@vindex anju-main-menu--reconfigure-file

The hook function @code{anju-main-menu--reconfigure-file} in @code{anju-reconfigure-main-menu-hook} modifies the @strong{File} menu in the main menu bar.

Enabling @code{anju-main-menu--reconfigure-file} can be done using the checkbox interface provided by @code{customize-variable} when modifying @code{anju-reconfigure-main-menu-hook}.

@code{anju-main-menu--reconfigure-file} supports the following customization variable:

@table @asis
@item @code{anju-file-menu-replace-make-frame-on}
If non-nil, the following menu items are replaced with more context-specific behavior:

@itemize
@item
“New Frame on Display Server@dots{}” - will only display if on an X11 system.
@item
“New Frame on Monitor@dots{}” - will only display if more than one monitor is detected.
@end itemize
@end table

@node Edit Menu Customization
@subsection Edit Menu Customization

@cindex Edit Menu Customization
@vindex anju-main-menu--reconfigure-edit

The hook function @code{anju-main-menu--reconfigure-edit} in @code{anju-reconfigure-main-menu-hook} modifies the @strong{Edit} menu in the main menu bar.

Enabling @code{anju-main-menu--reconfigure-edit} can be done using the checkbox interface provided by @code{customize-variable} when modifying @code{anju-reconfigure-main-menu-hook}.

@node Options Menu Customization
@subsection Options Menu Customization

@cindex Options Menu Customization
@vindex anju-main-menu--reconfigure-options

The hook function @code{anju-main-menu--reconfigure-options} in @code{anju-reconfigure-main-menu-hook} modifies the @strong{Options} menu in the main menu bar.

Enabling @code{anju-main-menu--reconfigure-options} can be done using the checkbox interface provided by @code{customize-variable} when modifying @code{anju-reconfigure-main-menu-hook}.

@node Text Menu Customization
@subsection Text Menu Customization

@cindex Text Menu Customization
@vindex anju-main-menu--reconfigure-text-mode

The hook function @code{anju-main-menu--reconfigure-text-mode} in @code{anju-reconfigure-main-menu-hook} modifies the @strong{Text} menu in the main menu bar.

Enabling @code{anju-main-menu--reconfigure-text-mode} can be done using the checkbox interface provided by @code{customize-variable} when modifying @code{anju-reconfigure-main-menu-hook}.

Note that the @strong{Text} menu is only displayed when the current major mode is derived from @code{text-mode}.

@node Bookmarks Menu Customization
@subsection Bookmarks Menu Customization

@cindex Bookmarks Menu Customization
@vindex anju-main-menu--reconfigure-bookmarks

The hook function @code{anju-main-menu--reconfigure-bookmarks} in @code{anju-reconfigure-main-menu-hook} adds the @strong{Bookmarks} menu to the main menu bar.

Enabling @code{anju-main-menu--reconfigure-bookmarks} can be done using the checkbox interface provided by @code{customize-variable} when modifying @code{anju-reconfigure-main-menu-hook}.

@node Help Menu Customization
@subsection Help Menu Customization

@cindex Help Menu Customization
@vindex anju-main-menu--reconfigure-help
@vindex anju-help-menu-remove-emacs-tutorial

The hook function @code{anju-main-menu--reconfigure-help} in @code{anju-reconfigure-main-menu-hook} modifies the @strong{Help} menu in the main menu bar.

Enabling @code{anju-main-menu--reconfigure-help} can be done using the checkbox interface provided by @code{customize-variable} in modifying @code{anju-reconfigure-main-menu-hook}.

@code{anju-main-menu--reconfigure-help} supports the following customization variable:

@table @asis
@item @code{anju-help-menu-remove-emacs-tutorial}
if non-nil, then remove the Emacs tutorial menu items. (default @code{t})
@end table

@node Imenu Menu Customization
@subsection Imenu Menu Customization

@cindex Imenu Menu Customization
@vindex anju-main-menu--reconfigure-imenu

The hook function @code{anju-main-menu--reconfigure-imenu} in @code{anju-reconfigure-main-menu-hook} adds the @strong{Index} menu to the main menu bar.

Enabling @code{anju-main-menu--reconfigure-file} can be done using the checkbox interface provided by @code{customize-variable} in modifying @code{anju-reconfigure-main-menu-hook}.

Anju's support for Imenu covers the following modes:

@itemize
@item
@code{prog-mode} derived modes
@item
@code{makefile-mode}
@item
@code{org-mode}
@item
@code{markdown-mode}
@end itemize

For more info on Imenu see @ref{Imenu,emacs#Imenu,,emacs,}.

@node Future Work
@chapter Future Work

@cindex Future Work

Work on Anju is on-going. Plans for future enhancements include:

@itemize
@item
Support for more built-in modes
@item
Further changes to the main menu
@end itemize

Although much consideration on both the user and developer experience has been made, they are both subject to change in future releases if a better approach presents itself.

@node Feedback & Discussion
@chapter Feedback & Discussion

@cindex Feedback
Please report any feedback about Anju to the @uref{https://github.com/kickingvegas/anju/issues, issue tracker on GitHub}.

@cindex Discussion
To participate in general discussion about using Anju, please join the @uref{https://github.com/kickingvegas/anju/discussions, discussion group}.

@node Sponsorship
@chapter Sponsorship

@cindex Sponsorship

It costs money to make, enhance, and maintain Anju as ideologically free software. If you enjoy using Anju, please buy me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas, buymeacoffee.com/kickingvegas}

@node About Anju
@chapter About Anju

@cindex About Anju

@uref{https://github.com/kickingvegas/anju, Anju} was conceived and crafted by Charles Choi in San Francisco, California.

Thank you for using Anju.

Always choose love.

@node Acknowledgments
@chapter Acknowledgments

@cindex Acknowledgments

Thanks goes out to the contributors to @code{mouse.el}, whose work this package builds upon.

@node Main Index
@chapter Main Index

Index for this user guide.

@printindex cp

@node Variable Index
@chapter Variable Index

Variables, functions, commands, and menus referenced by this user guide.

@printindex vr

@bye
