\input texinfo    @c -*- texinfo -*-
@c %**start of header
@setfilename anju.info
@settitle Anju User Guide
@documentencoding UTF-8
@documentlanguage en
@syncodeindex pg cp
@paragraphindent none
@c %**end of header

@copying
Copyright © 2026 Charles Y@. Choi
@end copying

@dircategory Emacs misc features
@direntry
* Anju: (anju).         A package for customizing Emacs mouse interactions.
@end direntry

@finalout
@titlepage
@title Anju User Guide
@subtitle for version 1.0.6-rc.1
@author Charles Y@. Choi (@email{kickingvegas@@gmail.com})
@page
@vskip 0pt plus 1filll
@insertcopying
@end titlepage

@contents

@ifnottex
@node Top
@top Anju User Guide

Version: 1.0.6-rc.1

Copyright © 2026 @w{Charles Y. Choi}

Anju (안주) is a project to align mouse interactions in Emacs with contemporary (circa 2026) expectations. Effort towards this alignment is made in the following areas:

@itemize
@item
Context-sensitive menus
@item
De-emphasis of middle mouse button usage (binding @samp{<mouse-2>})
@item
Support direct manipulation when possible
@item
Re-organization of the main menu bar
@end itemize

The features offered by Anju are opinionated, but avoids unconventional behavior. Anju aspires to bring a calmer mouse experience to Emacs.

Please note that all UI terminology in this document is Emacs-centric and differs from conventional GUI terminology. Refer to (emacs) Frames (@ref{Frames,emacs#Frames,,emacs,}) for more detail on this.

It costs money to make, enhance, and maintain Anju as ideologically free software. If you enjoy using Anju, please buy me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas}

@end ifnottex

@menu
* Motivation::
* Features::
* Requirements::
* Install::
* Customization::
* Future Work::
* Feedback & Discussion::
* Sponsorship::
* About Anju::
* Acknowledgments::
* Main Index::
* Variable Index::

@detailmenu
--- The Detailed Node Listing ---

Motivation

* Design Principles and Concerns::

Features

* Mode Line::
* Context Menu::
* Main Menu::
* Window Management::

Context Menu

* Selected Text Commands::
* Org Mode Context Menu::
* Dired Mode Context Menu::
* Magit Support::

Org Mode Context Menu

* Org Headline::
* Org Item::
* Org Table::

Customization

* Anju Initialization (@code{anju-init})::
* Context Menu Customization::
* Mode Line Buffer List Menu Customization::
* Main Menu Customization::

Context Menu Customization

* Anju Context Menu Functions::

@end detailmenu
@end menu

@node Motivation
@chapter Motivation

@cindex Motivation

The Anju package is intended to change the default mouse interactions in Emacs for the following reasons:

@itemize
@item
Uneven implementation of context-sensitive menus for different modes.
@item
Over-commitment to legacy usage of the middle mouse button.
@item
Lengthy menus that feel more like an inventory of commands rather than a designed user experience.
@item
Over-reliance on mouse workflows that require switching between the mouse and keyboard.
@end itemize

Anju makes opinionated design decisions, but avoids unconventional behavior. Anju aspires to bring a calmer mouse experience to Emacs.

Elaboration on what informs Anju's opinions is described below.

@menu
* Design Principles and Concerns::
@end menu

@node Design Principles and Concerns
@section Design Principles and Concerns

@cindex Design Principles and Concerns

This section conveys the principles and concerns used by Anju to inform its design decisions.

Editorially, all design decisions for Anju are ultimately the opinion of Charles Y@. Choi.


@subheading General Principles

@itemize
@item
Menus should be organized.
@itemize
@item
A coherent information architecture should be conveyed.
@item
Balance between concision and discoverability should be made in a menu's offerings.
@end itemize
@item
Nesting of sub-menus should be carefully considered, ideally not exceeding a depth of two.
@item
Mouse workflows that require keyboard input should be minimized.
@item
If the opportunity to provide a direct manipulation experience is available, it should be taken.
@item
Unconventional mouse interactions should be avoided.
@end itemize

@subheading Concerns

Anju takes the position that different types of menus have different concerns or objectives. This is most apparent in contrasting the design of a main menu section (e.g. File, Edit, Options, …) to that of a context menu.

For Anju:

@itemize
@item
The highest concern of a main menu section is discoverability.
@item
The highest concern of a context menu is concision.
@end itemize

A common implementation practice in Emacs is to reuse menu keymaps for both the main menu and context menus. This violates the above concerns, which Anju seeks to address.

The next sub-sections further detail the design concerns with respect to an area where mouse interaction occurs.

@subsubheading Context Menu

A context menu (as its name implies) should constrain itself to commands relevant to @emph{context}. The parameters of this context are usually (although not exclusively) defined by a subset of:

@itemize
@item
Point (cursor) position
@item
Text selection
@item
Mouse cursor position
@item
Major mode
@item
Read-only state (on or off)
@end itemize

Anju takes the opinion that context menus should @emph{not} support general command discovery. The context menu offering should be @emph{concise}. Users seeking command discovery should instead look at the main menu.

@subsubheading Direct Manipulation

Support for direct action based on mouse cursor position is a common user interaction technique. Anju applies this to Emacs window management, where window creation, deletion, and swapping are supported from both the context menu and the mode line.

@subsubheading No Middle Button Bindings

Anju eschews Emacs' default middle mouse button bindings as they presume usage of a @uref{https://upload.wikimedia.org/wikipedia/commons/thumb/e/ea/Sun_optical_mouse.jpg/960px-Sun_optical_mouse.jpg, 90's style 3-button mouse}. This style of mouse design has long been superseded with a middle @uref{https://upload.wikimedia.org/wikipedia/commons/2/22/3-Tasten-Maus_Microsoft.jpg, scroll-wheel+button control}. This widespread hardware change has resulted in the majority of mouse-supporting applications to emphasize scrolling actions with the middle control and clicking actions to the left and right buttons. Anju follows suit, primarily binding the right mouse button click (down) event to raising a context menu. In addition, Anju reconfigures commands that were previously bound to the middle button to ones accessible via a context menu.

The only exception Anju makes in this matter is to keep the Emacs default binding of @code{mouse-2} to @code{mouse-yank-primary}.

@node Features
@chapter Features

@cindex Features

Anju offers many enhancements to the mouse interactions provided by Emacs. These enhancements are detailed in the following sections below.

@menu
* Mode Line::
* Context Menu::
* Main Menu::
* Window Management::
@end menu

@node Mode Line
@section Mode Line

@cindex Mode Line

The following mode line enhancements are provided by Anju:

@subheading Pop-up Buffer List
@cindex Pop-up Buffer List

On the mode line, left-click (@code{mouse-1}) on the buffer name to raise a pop-up menu containing a list of open buffers. The contents of this list is controlled by the customizable variable @code{anju-buffer-list-filter-functions}. More info on customizing the buffer list menu can be found in @ref{Mode Line Buffer List Menu Customization}.


@image{images/anju-mode-line-buffer-list,,,,png}

@subheading Window Management
@cindex Window Management

A right-click (@code{mouse-3}) on any blank space on the mode line will pop-up a window management menu.

@image{images/anju-mode-line-window-management,,,,png}

From here, one can:
@itemize
@item
Delete the window (×)
@item
Split the window horizontally (→)
@item
Split the window vertically (↓)
@item
If multiple windows are shown, swap the current window.
@end itemize

Note: usage of ``window'' refers to the Emacs definition of it. Refer to @ref{Frames,emacs#Frames,,emacs,} for more detail on this.

@subheading Toggle Maximize Window
@cindex Toggle Maximize Window

A left-double-click on any blank space on the mode line will checkpoint the current window configuration, then maximize the current window (@code{delete-other-windows}). Re-doing the left-double-click will restore the prior window configuration.

@node Context Menu
@section Context Menu

@cindex Context Menu

Anju enhances @code{context-menu-mode} by providing context menu functions to support the following contexts:

@itemize
@item
Selected text
@item
Mode-specific commands
@itemize
@item
Org mode
@item
Dired
@end itemize
@item
Window management
@item
Full support for @code{context-menu-mode} customization (See @ref{Context Menu Customization}).
@end itemize

Anju deliberately omits the display of the default mode-specific menu keymaps in the context menu as they are considered redundant to their display in the main menu. Rationale for this is described in @ref{Design Principles and Concerns}. Users can still access the default mode-specific menu keymap by using the binding @kbd{C-<mouse-3>}.



Learn more about the different areas Anju enhances context menus in the links below.

@menu
* Selected Text Commands::
* Org Mode Context Menu::
* Dired Mode Context Menu::
* Magit Support::
@end menu

@node Selected Text Commands
@subsection Selected Text Commands

@cindex Selected Text Commands

@image{images/anju-context-menu-region,,,,png}

If a context menu is raised on selected text, the following menu items are displayed:

@table @asis
@item Style
Applies mode-specific markup to emphasize the selected text (e.g. bold, italic, code, etc.).
@itemize
@item
Available only for @code{org-mode} and @code{markdown-mode}.
@end itemize

@item Transform Text
Applies transforms (upper/lower case, capitalize) to the selected text.

@item Occur
Run @code{occur} command to show occurrences of selected text.

@item Toggle comment 
Toggles selected text to be commented based on mode.
@itemize
@item
Available only on modes derived from @code{prog-mode} and @code{org-mode}
@end itemize

@item Write Region
Writes selected text to a user-specified file.
@end table

@node Org Mode Context Menu
@subsection Org Mode Context Menu

@cindex Org Mode Context Menu

Anju provides context-sensitive support for Org mode by providing commands relevant to the type of Org element the point is in. Org elements supported by Anju are:

@itemize
@item
Headline
@item
Item
@item
Table
@end itemize

In addition if text is selected, then support for styling it is supported.

Note that the Org mode context menu is intentionally restrained in its command offering in accord with Anju's @ref{Design Principles and Concerns}.

It is recommended that the @code{org-mouse} package be loaded when using

@menu
* Org Headline::
* Org Item::
* Org Table::
@end menu

@node Org Headline
@subsubsection Org Headline

If the context menu is raised on a headline, then commands related to clocking and promotion are offered.

@image{images/anju-context-menu-org-headline,,,,png}

@node Org Item
@subsubsection Org Item

If the context menu is raised on a list item, then commands related to promotion and conversion to a checkbox are provided.

The menu item ``To Checkbox'' will convert an item to a checkbox, with the additional behavior that if the point is at the start of the whole list, the whole list will be turned into checkboxes.

@image{images/anju-context-menu-org-item,,,,png}

If @code{org-mouse} is loaded, then clicking on a checkbox will toggle its state between on ('[X]') or off ('[ ]'). However, changing to an intermediate state ('[-]') is supported by the menu item ``In-Progress''. The menu item ``To Item'' will convert the checkbox back to a plain list item.

@image{images/anju-context-menu-org-checkbox,,,,png}

Note that checkboxes in screenshots are prettified using @code{prettify-symbols-mode}.

@node Org Table
@subsubsection Org Table

If the context menu is raised in a table, then table-specific commands are shown.

@image{images/anju-context-menu-org-table,,,,png}

@node Dired Mode Context Menu
@subsection Dired Mode Context Menu

@cindex Dired Mode Context Menu

Anju has context menu support for Dired mode. The screenshot below shows the context menu when the mouse point is over a file.

@image{images/anju-dired-copy-to,,,,png}

If the mouse point is over a directory, the option to insert a view (aka subdir) for it in the buffer is provided.

@image{images/anju-dired-insert-subdir,,,,png}

Note that the Dired context menu is intentionally restrained in its command offering in accord with Anju's @ref{Design Principles and Concerns}.

@node Magit Support
@subsection Magit Support

@cindex Magit Support

If Magit 4.4+ is installed, then the context menu function @code{anju-context-menu-vc} will offer Magit commands depending on context. If the context menu is raised in a file buffer, then the menu item ``Magit Dispatch…'' (@code{magit-file-dispatch}) is shown, otherwise ``Magit Status'' (@code{magit-status}).

@node Main Menu
@section Main Menu

@cindex Main Menu

Anju offers the following enhancements to the main menu:

@subheading Bookmarks menu

To support usage of Emacs bookmarks, the following menu is added to the main menu.

@image{images/anju-main-menu-bookmarks,,,,png}


@subheading Index menu (imenu)

Anju adds the index menu (@ref{Imenu,emacs#Imenu,,emacs,}) to the main menu bar for modes that support it. Anju will configure the following modes with @code{imenu-add-menubar-index}:

@itemize
@item
@code{prog-mode} derived modes
@item
@code{makefile-mode}
@item
@code{org-mode}
@item
@code{markdown-mode}
@end itemize



@subheading Help menu

An opinionated re-organization of the Help menu is provided.

@image{images/anju-main-menu-help,,,,png}

Anju provides support for customizing all the above enhancements to the main menu. See @ref{Main Menu Customization} for more detail.

@node Window Management
@section Window Management

@cindex Window Management

Window management via mouse interaction is provided for through the @ref{Mode Line, , mode line} and @ref{Context Menu, , context menu}. More detail is provided in those sections.

@node Requirements
@chapter Requirements

@cindex Requirements

Anju requires Emacs 29.1+, Casual 2.13+, Markdown Mode 2.7+.

Certain menus require more installed software:

@itemize
@item
Anju Dired Support: GNU Coreutils (@code{ls})
@item
Markdown import to Org: pandoc
@end itemize

Anju provides optional support for Magit 4.4+.

@node Install
@chapter Install

@cindex Install
@vindex context-menu-mode
@vindex anju-init

Basic installation of Anju composes of two parts:

@enumerate
@item
Turn on @code{context-menu-mode} to major modes of preference. This is done using the @code{add-hook} function as shown below.
@lisp
(add-hook 'prog-mode-hook #'context-menu-mode)
(add-hook 'text-mode-hook #'context-menu-mode)
(add-hook 'dired-mode-hook #'context-menu-mode)
(add-hook 'shell-mode-hook #'context-menu-mode)
@end lisp

@item
Call @code{anju-init} in your Emacs initialization file.

@lisp
(anju-init)
@end lisp
@end enumerate

Anju supports a high degree of customization. Users who wish this should make a deep read of the @ref{Customization} section.

While not required, the following additions to your Emacs initialization file can further enhance your mouse experience:

@itemize
@item
Enable @code{org-mouse}
@lisp
(require 'org-mouse)
@end lisp

@item
Add Markdown export support to Org mode
@itemize
@item
@code{M-x} @code{customize-variable} @code{org-export-backends}, check @code{md} option.
@end itemize

@item
Globally bind @code{C-x 1} to @code{anju-toggle-one-window}.

@lisp
(keymap-global-set "C-x 1" #'anju-toggle-one-window)
@end lisp

@item
Set @code{use-file-dialog} to @code{t} to support mouse-driven-only dialog interactions, or @code{nil} to always get a mini-buffer prompt.
@end itemize

@node Customization
@chapter Customization

@cindex Customization

Anju provides a number of ways to customize mouse interactions in Emacs. In many cases, Anju leverages off existing Emacs customization options, particularly around defining and modifying menus. Users who wish to modify menus in Emacs should familiarize themselves with menu keymaps (@ref{Menu Keymaps,elisp#Menu Keymaps,,elisp,}) and the Easy Menu (@ref{Easy Menu,elisp#Easy Menu,,elisp,}) library.

Customization options for the different areas Anju covers are detailed below.

@menu
* Anju Initialization (@code{anju-init})::
* Context Menu Customization::
* Mode Line Buffer List Menu Customization::
* Main Menu Customization::
@end menu

@node Anju Initialization (@code{anju-init})
@section Anju Initialization (@code{anju-init})

@cindex Anju Initialization
@vindex anju-init
@vindex anju-reconfigure-context-menu-functions-enable
@vindex anju-mode-line-bindings-enable
@vindex anju-unset-legacy-mouse-bindings-enable
@vindex anju-reconfigure-main-menu-enable
@vindex anju-help-menu-remove-emacs-tutorial
@vindex anju-reconfigure-main-menu-hook

Anju has a number of customizable variables that determine the behavior of @code{anju-init}. They are:

@table @asis
@item @code{anju-reconfigure-context-menu-functions-enable}
Enable reconfiguration of the variable @code{context-menu-functions} with Anju-defined menu functions.

If @code{context-menu-functions} is previously set via @code{customize-variable} then @code{anju-init} will make no changes to @code{context-menu-functions} regardless of how  @code{anju-reconfigure-context-menu-functions-enable} is set.

@item @code{anju-mode-line-bindings-enable}
Enable Anju-defined bindings for the mode line.

@item @code{anju-unset-legacy-mouse-bindings-enable}
Remove bindings using @code{mouse-2}.

@item @code{anju-reconfigure-main-menu-enable}
Top-level variable to reconfigure the main menu.

If @code{anju-reconfigure-main-menu-enable} is @code{t}, the following variables determine how the main menu is reconfigured:

@table @asis
@item @code{anju-reconfigure-main-menu-hook}
a list of functions, each modifying a sub-menu of the main menu.

@item @code{anju-help-menu-remove-emacs-tutorial}
control if the Emacs tutorial menu items are shown.
@end table
@end table

By default, all the above @code{*-enable} variables are set to @code{t}.  Users preferring to make granular changes to @code{anju-init} can invoke @code{M-x} @code{customize-group} @code{anju}.

@node Context Menu Customization
@section Context Menu Customization

@cindex Context Menu Customization
@vindex context-menu-mode
@vindex context-menu-functions


Anju uses @code{context-menu-mode} (introduced in Emacs 28) to define its context menu behavior. This is accomplished through the customizable hook variable @code{context-menu-functions}.

@code{context-menu-functions} is a list of functions where each function has two arguments:

@itemize
@item
@code{menu} : reference to the context menu
@item
@code{click} : a mouse event
@end itemize

When the context menu is raised, typically via right-click (@code{mouse-3}), each function in @code{context-menu-functions} is run, populating the context menu.

The following example Elisp illustrates an implementation of a context menu function.

@lisp
(defun anju-context-menu-wordcount (menu click)
  "Context menu hook function for wordcount commands.

- MENU: menu
- CLICK: event

This function is intended to be hooked into `context-menu-functions'."

  (save-excursion
    (mouse-set-point click)

    (when (derived-mode-p 'text-mode) ; context predicate
      (anju-context-menu-item-separator menu count-words-separator)
      (easy-menu-add-item menu nil ["Count Words"
                                    count-words
                                    :help "Count words"])))
  menu)
@end lisp


Defining how a menu item is context-sensitive can be determined in multiple places:

@enumerate
@item
At the time of menu item definition
@item
At a higher level.
@end enumerate

The @emph{context} is determined by a predicate which can take into account different things, among them:

@itemize
@item
Selected Text (@code{use-region-p})
@item
Major mode
@item
Cursor (Point) position
@item
Mouse position
@end itemize

In the example above, the context predicate is @code{(derived-mode-p 'text-mode)}.  Note that it is defined at a higher level to avoid instantiating menu items if the context does not apply.

The context predicate can be embedded in the menu item definition itself. See more about this with the @code{:visible} and @code{:active} keywords for the macro @code{easy-menu-define}.

It is up to the implementer to determine where to best apply the context predicate.

@subheading Customizing context-menu-functions

It is recommended to use the @code{customize-variable} command to configure @code{context-menu-functions} instead of using @code{add-hook} for the following reasons:

@enumerate
@item
A visual UI is provided showing what choices for built-in context menu functions are available.
@item
Users can insert their own custom function.
@item
Top-down ordering of functions will similarly determine the order of menu items in the context menu.
@end enumerate

@menu
* Anju Context Menu Functions::
@end menu

@node Anju Context Menu Functions
@subsection Anju Context Menu Functions

@vindex anju-context-menu-dired
@vindex anju-context-menu-org-mode
@vindex anju-context-menu-scratch
@vindex anju-context-menu-buffers
@vindex anju-context-menu-region
@vindex anju-context-menu-narrow
@vindex anju-context-menu-open-in
@vindex anju-context-menu-vc
@vindex anju-context-menu-markup
@vindex anju-context-menu-wordcount
@vindex anju-context-menu-window

Anju provides the following context menu functions for convenience. They can be used as-is or serve as a base for user-customized behavior.

@table @asis
@item @code{anju-context-menu-dired}
Dired commands.

@item @code{anju-context-menu-org-mode} 
Org mode commands.

@item @code{anju-context-menu-scratch} 
Open scratch buffer.

@item @code{anju-context-menu-buffers}
Buffer navigation commands.

@item @code{anju-context-menu-region}
Commands for selected text.

@item @code{anju-context-menu-narrow}
Narrow-related commands.

@item @code{anju-context-menu-open-in}
Open in Dired.

@item @code{anju-context-menu-vc}
Version control related commands.
If Magit 4.4+ is installed, then calls to it are made from here.

@item @code{anju-context-menu-markup}
Commands to show/hide text markup (e.g. Org, Markdown).

@item @code{anju-context-menu-wordcount}
Word count command.

@item @code{anju-context-menu-window}
Window management commands.
@end table

@node Mode Line Buffer List Menu Customization
@section Mode Line Buffer List Menu Customization

@cindex Mode Line Buffer List Menu Customization
@vindex anju-buffer-list-filter-functions
@vindex anju-mode-line-buffer-list-function
@vindex anju-buffer-list-plain-filter
@vindex anju-buffer-list-compilation-filter
@vindex anju-buffer-list-grep-filter
@vindex anju-buffer-list-xref-filter
@vindex anju-buffer-list-eshell-filter
@vindex anju-buffer-list-shell-filter
@vindex anju-buffer-list-info-filter
@vindex anju-buffer-list-help-filter
@vindex anju-buffer-list-menu-items
@vindex anju-popup-buffer-menu

The pop-up buffer list menu can be customized two ways:

@enumerate
@item
Customizing the variable @code{anju-buffer-list-filter-functions}, a list of filter functions that are run each time the pop-up menu is raised when left-clicking the mode line buffer name.

@item
Customizing the variable @code{anju-mode-line-buffer-list-function}, which gives a user complete control on what is displayed in the pop-up menu.
@end enumerate


@subheading anju-buffer-list-filter-functions

This variable is an alist used by the function @code{anju-buffer-list-menu-items} to populate the list of buffers used in the pop up menu @code{anju-popup-buffer-menu}.

This alist is filled using the following key, value pair types:

@table @asis
@item key
a buffer list filter function
@item value
integer used as the maximum count of buffers to use from the filter function
@end table

The buffer list filter function is of the form @code{(filter-fn (buffers &optional count))} where buffers is a list of buffers (usually @code{buffer-list}) and count is the maximum count of buffers to use.

The order of the buffer list presumes the most recently used buffers are
at the front of the list.

Anju provides the following buffer filters:

@table @asis
@item @code{anju-buffer-list-plain-filter}
buffers whose name is not marked as special (a name wrapped in ‘*’).
@item @code{anju-buffer-list-compilation-filter}
buffers whose major mode is @code{compilation-mode}.
@item @code{anju-buffer-list-grep-filter}
buffers whose major mode is @code{grep-mode}.
@item @code{anju-buffer-list-xref-filter}
buffers whose major mode is @code{xref--xref-buffer-mode}.
@item @code{anju-buffer-list-eshell-filter}
buffers whose major mode is @code{eshell-mode.}
@item @code{anju-buffer-list-shell-filter}
buffers whose major mode is @code{shell-mode}.
@item @code{anju-buffer-list-info-filter}
buffers whose major mode is @code{Info-mode}.
@item @code{anju-buffer-list-help-filter}
buffers whose major mode is @code{help-mode}.
@end table

Users can customize @code{anju-buffer-list-filter-functions} to re-compose or add their own filters to define the resulting buffer list returned by @code{anju-buffer-list-menu-items}. It is recommended that the @code{customize-variable} command be used to accomplish this.

@subheading anju-mode-line-buffer-list-function
@vindex anju-mode-line-buffer-list-function

Function that populates the mode line buffer name popup menu.

Assign this variable to a function that returns a value that conforms to the @code{MENU} parameter of the command @code{popup-menu}.

This setting allows for customization of the buffer list (or any other menu content) when the mode line buffer name (identifier) is clicked (typically with @code{mouse-1}).

Users who wish define their own menu should override this value with their own function. It is recommended that such users look at the source to @code{anju-buffer-list-menu-items} as a start to defining their own menu function.

@node Main Menu Customization
@section Main Menu Customization

@cindex Main Menu Customization
@vindex anju-main-menu--reconfigure-text-mode
@vindex anju-main-menu--reconfigure-bookmarks
@vindex anju-main-menu--reconfigure-help
@vindex anju-main-menu--reconfigure-imenu
@vindex anju-help-menu-remove-emacs-tutorial

Anju modifies the main menu via the customizable hook variable @code{anju-reconfigure-main-menu-hook}. This hook is run in the command @code{anju-init}.

By default, the following hook functions are run:

@table @asis
@item @code{anju-main-menu--reconfigure-text-mode}
Reconfigures Text menu for text mode buffers.

@item @code{anju-main-menu--reconfigure-bookmarks}
Adds Bookmarks menu to main menu.

@item @code{anju-main-menu--reconfigure-help}
Reconfigures Help menu.
@itemize
@item
Set the customizable variable @code{anju-help-menu-remove-emacs-tutorial} to @code{t} if removing the tutorial entries is desired.
@end itemize

@item @code{anju-main-menu--reconfigure-imenu}
Adds an index menu (imenu) to the following modes:
@itemize
@item
@code{prog-mode}
@item
@code{makefile-mode}
@item
@code{org-mode}
@item
@code{markdown-mode}
@end itemize
@end table

Execution of any of the above functions can be set to preference in @code{anju-reconfigure-main-menu-hook}.    

@code{anju-reconfigure-main-menu-hook} can be modified to add additional custom hook functions. Users who wish to do this should familiarize themselves with menu keymaps (@ref{Menu Keymaps,elisp#Menu Keymaps,,elisp,}) and the Easy Menu (@ref{Easy Menu,elisp#Easy Menu,,elisp,}) library.

Shown below is an example Elisp function which modifies the “Text” menu section of the main menu for modes which derive from @code{text-mode}.

@lisp
(defun anju-main-menu--reconfigure-text-mode ()
  "Reconfigure Text mode menu."
  (easy-menu-remove-item text-mode-menu nil "Center Line")
  (easy-menu-remove-item text-mode-menu nil "Center Region")
  (easy-menu-remove-item text-mode-menu nil "Center Paragraph")
  (easy-menu-remove-item text-mode-menu nil "Paragraph Indent")
  (easy-menu-remove-item text-mode-menu nil "---")

  (easy-menu-add-item text-mode-menu nil anju-transform-text-menu "Auto Fill")
  (easy-menu-add-item text-mode-menu nil anju-style-menu "Auto Fill"))
@end lisp

@node Future Work
@chapter Future Work

@cindex Future Work

Work on Anju is on-going. Plans for future enhancements include:

@itemize
@item
Support for more built-in modes
@item
Further changes to the main menu
@end itemize

Although much consideration on both the user and developer experience has been made, they are both subject to change in future releases if a better approach presents itself.

@node Feedback & Discussion
@chapter Feedback & Discussion

@cindex Feedback
Please report any feedback about Anju to the @uref{https://github.com/kickingvegas/anju/issues, issue tracker on GitHub}.

@cindex Discussion
To participate in general discussion about using Anju, please join the @uref{https://github.com/kickingvegas/anju/discussions, discussion group}.

@node Sponsorship
@chapter Sponsorship

@cindex Sponsorship

It costs money to make, enhance, and maintain Anju as ideologically free software. If you enjoy using Anju, please buy me a coffee to help support its development and maintenance.

@image{images/default-yellow,,,,png}

@uref{https://www.buymeacoffee.com/kickingvegas, buymeacoffee.com/kickingvegas}

@node About Anju
@chapter About Anju

@cindex About Anju

@uref{https://github.com/kickingvegas/anju, Anju} was conceived and crafted by Charles Choi in San Francisco, California.

Thank you for using Anju.

Always choose love.

@node Acknowledgments
@chapter Acknowledgments

@cindex Acknowledgments

Thanks goes out to the contributors to @code{mouse.el}, whose work this package builds upon.

@node Main Index
@chapter Main Index

Index for this user guide.

@printindex cp

@node Variable Index
@chapter Variable Index

Variables, functions, commands, and menus referenced by this user guide.

@printindex vr

@bye
